baseURL = "https://krepodzh.github.io/"
languageCode = "ru"
title = "Журнал исследователя жизни. Алихан Хабибулла."
theme = "PaperMod"
[pagination]
  pagerSize = 10
enableRobotsTXT = true

[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
  defaultTheme = "auto"
  ShowReadingTime = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowShareButtons = false
  ShowToc = false

[menu]
[[menu.main]]
  name = "Лента"
  url = "/"
  weight = 1
[[menu.main]]
  name = "RSS"
  url = "/index.xml"
  weight = 2
